/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConteNosRouteImport } from './routes/conte-nos'
import { Route as CultosRouteImport } from './routes/cultos'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as MinisteriosRouteImport } from './routes/ministerios'
import { Route as MusicaRouteImport } from './routes/musica'
import { Route as NovoAquiRouteImport } from './routes/novo-aqui'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as OracaoRouteImport } from './routes/oracao'
import { Route as ProximoPassoRouteImport } from './routes/proximo-passo'
import { Route as ServirRouteImport } from './routes/servir'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MusicaIndexRouteImport } from './routes/musica.index'
import { Route as MusicaBibliotecaRouteImport } from './routes/musica.biblioteca'
import { Route as MusicaBuscaRouteImport } from './routes/musica.busca'
import { Route as MusicaAlbumSlugRouteImport } from './routes/musica.album.$slug'
import { Route as MusicaArtistaSlugRouteImport } from './routes/musica.artista.$slug'
import { Route as MusicaFaixaSlugRouteImport } from './routes/musica.faixa.$slug'
import { Route as MusicaPlaylistSlugRouteImport } from './routes/musica.playlist.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteNosRoute = ConteNosRouteImport.update({
  id: '/conte-nos',
  path: '/conte-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const CultosRoute = CultosRouteImport.update({
  id: '/cultos',
  path: '/cultos',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisteriosRoute = MinisteriosRouteImport.update({
  id: '/ministerios',
  path: '/ministerios',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicaRoute = MusicaRouteImport.update({
  id: '/musica',
  path: '/musica',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoAquiRoute = NovoAquiRouteImport.update({
  id: '/novo-aqui',
  path: '/novo-aqui',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const OracaoRoute = OracaoRouteImport.update({
  id: '/oracao',
  path: '/oracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximoPassoRoute = ProximoPassoRouteImport.update({
  id: '/proximo-passo',
  path: '/proximo-passo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServirRoute = ServirRouteImport.update({
  id: '/servir',
  path: '/servir',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicaIndexRoute = MusicaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MusicaRoute,
} as any)
const MusicaBibliotecaRoute = MusicaBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => MusicaRoute,
} as any)
const MusicaBuscaRoute = MusicaBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => MusicaRoute,
} as any)
const MusicaAlbumSlugRoute = MusicaAlbumSlugRouteImport.update({
  id: '/album/$slug',
  path: '/album/$slug',
  getParentRoute: () => MusicaRoute,
} as any)
const MusicaArtistaSlugRoute = MusicaArtistaSlugRouteImport.update({
  id: '/artista/$slug',
  path: '/artista/$slug',
  getParentRoute: () => MusicaRoute,
} as any)
const MusicaFaixaSlugRoute = MusicaFaixaSlugRouteImport.update({
  id: '/faixa/$slug',
  path: '/faixa/$slug',
  getParentRoute: () => MusicaRoute,
} as any)
const MusicaPlaylistSlugRoute = MusicaPlaylistSlugRouteImport.update({
  id: '/playlist/$slug',
  path: '/playlist/$slug',
  getParentRoute: () => MusicaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/conte-nos': typeof ConteNosRoute
  '/cultos': typeof CultosRoute
  '/mensagens': typeof MensagensRoute
  '/ministerios': typeof MinisteriosRoute
  '/musica': typeof MusicaRouteWithChildren
  '/novo-aqui': typeof NovoAquiRoute
  '/ofertas': typeof OfertasRoute
  '/oracao': typeof OracaoRoute
  '/proximo-passo': typeof ProximoPassoRoute
  '/servir': typeof ServirRoute
  '/sobre': typeof SobreRoute
  '/musica/biblioteca': typeof MusicaBibliotecaRoute
  '/musica/busca': typeof MusicaBuscaRoute
  '/musica/': typeof MusicaIndexRoute
  '/musica/album/$slug': typeof MusicaAlbumSlugRoute
  '/musica/artista/$slug': typeof MusicaArtistaSlugRoute
  '/musica/faixa/$slug': typeof MusicaFaixaSlugRoute
  '/musica/playlist/$slug': typeof MusicaPlaylistSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/conte-nos': typeof ConteNosRoute
  '/cultos': typeof CultosRoute
  '/mensagens': typeof MensagensRoute
  '/ministerios': typeof MinisteriosRoute
  '/novo-aqui': typeof NovoAquiRoute
  '/ofertas': typeof OfertasRoute
  '/oracao': typeof OracaoRoute
  '/proximo-passo': typeof ProximoPassoRoute
  '/servir': typeof ServirRoute
  '/sobre': typeof SobreRoute
  '/musica/biblioteca': typeof MusicaBibliotecaRoute
  '/musica/busca': typeof MusicaBuscaRoute
  '/musica': typeof MusicaIndexRoute
  '/musica/album/$slug': typeof MusicaAlbumSlugRoute
  '/musica/artista/$slug': typeof MusicaArtistaSlugRoute
  '/musica/faixa/$slug': typeof MusicaFaixaSlugRoute
  '/musica/playlist/$slug': typeof MusicaPlaylistSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contato': typeof ContatoRoute
  '/conte-nos': typeof ConteNosRoute
  '/cultos': typeof CultosRoute
  '/mensagens': typeof MensagensRoute
  '/ministerios': typeof MinisteriosRoute
  '/musica': typeof MusicaRouteWithChildren
  '/novo-aqui': typeof NovoAquiRoute
  '/ofertas': typeof OfertasRoute
  '/oracao': typeof OracaoRoute
  '/proximo-passo': typeof ProximoPassoRoute
  '/servir': typeof ServirRoute
  '/sobre': typeof SobreRoute
  '/musica/biblioteca': typeof MusicaBibliotecaRoute
  '/musica/busca': typeof MusicaBuscaRoute
  '/musica/': typeof MusicaIndexRoute
  '/musica/album/$slug': typeof MusicaAlbumSlugRoute
  '/musica/artista/$slug': typeof MusicaArtistaSlugRoute
  '/musica/faixa/$slug': typeof MusicaFaixaSlugRoute
  '/musica/playlist/$slug': typeof MusicaPlaylistSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/conte-nos'
    | '/cultos'
    | '/mensagens'
    | '/ministerios'
    | '/musica'
    | '/novo-aqui'
    | '/ofertas'
    | '/oracao'
    | '/proximo-passo'
    | '/servir'
    | '/sobre'
    | '/musica/biblioteca'
    | '/musica/busca'
    | '/musica/'
    | '/musica/album/$slug'
    | '/musica/artista/$slug'
    | '/musica/faixa/$slug'
    | '/musica/playlist/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contato'
    | '/conte-nos'
    | '/cultos'
    | '/mensagens'
    | '/ministerios'
    | '/novo-aqui'
    | '/ofertas'
    | '/oracao'
    | '/proximo-passo'
    | '/servir'
    | '/sobre'
    | '/musica/biblioteca'
    | '/musica/busca'
    | '/musica'
    | '/musica/album/$slug'
    | '/musica/artista/$slug'
    | '/musica/faixa/$slug'
    | '/musica/playlist/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/conte-nos'
    | '/cultos'
    | '/mensagens'
    | '/ministerios'
    | '/musica'
    | '/novo-aqui'
    | '/ofertas'
    | '/oracao'
    | '/proximo-passo'
    | '/servir'
    | '/sobre'
    | '/musica/biblioteca'
    | '/musica/busca'
    | '/musica/'
    | '/musica/album/$slug'
    | '/musica/artista/$slug'
    | '/musica/faixa/$slug'
    | '/musica/playlist/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContatoRoute: typeof ContatoRoute
  ConteNosRoute: typeof ConteNosRoute
  CultosRoute: typeof CultosRoute
  MensagensRoute: typeof MensagensRoute
  MinisteriosRoute: typeof MinisteriosRoute
  MusicaRoute: typeof MusicaRouteWithChildren
  NovoAquiRoute: typeof NovoAquiRoute
  OfertasRoute: typeof OfertasRoute
  OracaoRoute: typeof OracaoRoute
  ProximoPassoRoute: typeof ProximoPassoRoute
  ServirRoute: typeof ServirRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conte-nos': {
      id: '/conte-nos'
      path: '/conte-nos'
      fullPath: '/conte-nos'
      preLoaderRoute: typeof ConteNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultos': {
      id: '/cultos'
      path: '/cultos'
      fullPath: '/cultos'
      preLoaderRoute: typeof CultosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministerios': {
      id: '/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof MinisteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musica': {
      id: '/musica'
      path: '/musica'
      fullPath: '/musica'
      preLoaderRoute: typeof MusicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-aqui': {
      id: '/novo-aqui'
      path: '/novo-aqui'
      fullPath: '/novo-aqui'
      preLoaderRoute: typeof NovoAquiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracao': {
      id: '/oracao'
      path: '/oracao'
      fullPath: '/oracao'
      preLoaderRoute: typeof OracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximo-passo': {
      id: '/proximo-passo'
      path: '/proximo-passo'
      fullPath: '/proximo-passo'
      preLoaderRoute: typeof ProximoPassoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servir': {
      id: '/servir'
      path: '/servir'
      fullPath: '/servir'
      preLoaderRoute: typeof ServirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musica/': {
      id: '/musica/'
      path: '/'
      fullPath: '/musica/'
      preLoaderRoute: typeof MusicaIndexRouteImport
      parentRoute: typeof MusicaRoute
    }
    '/musica/biblioteca': {
      id: '/musica/biblioteca'
      path: '/biblioteca'
      fullPath: '/musica/biblioteca'
      preLoaderRoute: typeof MusicaBibliotecaRouteImport
      parentRoute: typeof MusicaRoute
    }
    '/musica/busca': {
      id: '/musica/busca'
      path: '/busca'
      fullPath: '/musica/busca'
      preLoaderRoute: typeof MusicaBuscaRouteImport
      parentRoute: typeof MusicaRoute
    }
    '/musica/album/$slug': {
      id: '/musica/album/$slug'
      path: '/album/$slug'
      fullPath: '/musica/album/$slug'
      preLoaderRoute: typeof MusicaAlbumSlugRouteImport
      parentRoute: typeof MusicaRoute
    }
    '/musica/artista/$slug': {
      id: '/musica/artista/$slug'
      path: '/artista/$slug'
      fullPath: '/musica/artista/$slug'
      preLoaderRoute: typeof MusicaArtistaSlugRouteImport
      parentRoute: typeof MusicaRoute
    }
    '/musica/faixa/$slug': {
      id: '/musica/faixa/$slug'
      path: '/faixa/$slug'
      fullPath: '/musica/faixa/$slug'
      preLoaderRoute: typeof MusicaFaixaSlugRouteImport
      parentRoute: typeof MusicaRoute
    }
    '/musica/playlist/$slug': {
      id: '/musica/playlist/$slug'
      path: '/playlist/$slug'
      fullPath: '/musica/playlist/$slug'
      preLoaderRoute: typeof MusicaPlaylistSlugRouteImport
      parentRoute: typeof MusicaRoute
    }
  }
}

interface MusicaRouteChildren {
  MusicaBibliotecaRoute: typeof MusicaBibliotecaRoute
  MusicaBuscaRoute: typeof MusicaBuscaRoute
  MusicaIndexRoute: typeof MusicaIndexRoute
  MusicaAlbumSlugRoute: typeof MusicaAlbumSlugRoute
  MusicaArtistaSlugRoute: typeof MusicaArtistaSlugRoute
  MusicaFaixaSlugRoute: typeof MusicaFaixaSlugRoute
  MusicaPlaylistSlugRoute: typeof MusicaPlaylistSlugRoute
}

const MusicaRouteChildren: MusicaRouteChildren = {
  MusicaBibliotecaRoute: MusicaBibliotecaRoute,
  MusicaBuscaRoute: MusicaBuscaRoute,
  MusicaIndexRoute: MusicaIndexRoute,
  MusicaAlbumSlugRoute: MusicaAlbumSlugRoute,
  MusicaArtistaSlugRoute: MusicaArtistaSlugRoute,
  MusicaFaixaSlugRoute: MusicaFaixaSlugRoute,
  MusicaPlaylistSlugRoute: MusicaPlaylistSlugRoute,
}

const MusicaRouteWithChildren =
  MusicaRoute._addFileChildren(MusicaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContatoRoute: ContatoRoute,
  ConteNosRoute: ConteNosRoute,
  CultosRoute: CultosRoute,
  MensagensRoute: MensagensRoute,
  MinisteriosRoute: MinisteriosRoute,
  MusicaRoute: MusicaRouteWithChildren,
  NovoAquiRoute: NovoAquiRoute,
  OfertasRoute: OfertasRoute,
  OracaoRoute: OracaoRoute,
  ProximoPassoRoute: ProximoPassoRoute,
  ServirRoute: ServirRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
